// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYskJ7ooZ-yUcrEfPA9i3jwQWU7Gp9IGo',
    appId: '1:260320264999:web:7fbe35e41a82bb0fba1f02',
    messagingSenderId: '260320264999',
    projectId: 'flutterassignment-e93cb',
    authDomain: 'flutterassignment-e93cb.firebaseapp.com',
    storageBucket: 'flutterassignment-e93cb.firebasestorage.app',
    measurementId: 'G-5S2DFX38G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBGmEOj1ly9XFVRkq4Ae-J0-s5vSxDNkA',
    appId: '1:260320264999:android:7dceaf7a19d87075ba1f02',
    messagingSenderId: '260320264999',
    projectId: 'flutterassignment-e93cb',
    storageBucket: 'flutterassignment-e93cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVB2Dj_sc5q_VYgNmBhH1hUgeF2WnrOKk',
    appId: '1:260320264999:ios:fc73966af3e12dc5ba1f02',
    messagingSenderId: '260320264999',
    projectId: 'flutterassignment-e93cb',
    storageBucket: 'flutterassignment-e93cb.firebasestorage.app',
    iosBundleId: 'com.example.myAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVB2Dj_sc5q_VYgNmBhH1hUgeF2WnrOKk',
    appId: '1:260320264999:ios:fc73966af3e12dc5ba1f02',
    messagingSenderId: '260320264999',
    projectId: 'flutterassignment-e93cb',
    storageBucket: 'flutterassignment-e93cb.firebasestorage.app',
    iosBundleId: 'com.example.myAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYskJ7ooZ-yUcrEfPA9i3jwQWU7Gp9IGo',
    appId: '1:260320264999:web:2cf7d5a2778146deba1f02',
    messagingSenderId: '260320264999',
    projectId: 'flutterassignment-e93cb',
    authDomain: 'flutterassignment-e93cb.firebaseapp.com',
    storageBucket: 'flutterassignment-e93cb.firebasestorage.app',
    measurementId: 'G-P1LZ5REQWK',
  );
}
